# Generated by Django 2.1.3 on 2018-11-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text="Student's Name", max_length=200)),
                ('roll_no', models.CharField(help_text="Student's Roll Number", max_length=50)),
            ],
        ),
    ]
