# Generated by Django 2.1.3 on 2018-11-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='admit_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='dob',
            field=models.DateField(blank=True, help_text="Student's Date of Birth", null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='student_name',
            field=models.CharField(help_text="Student's Full Name", max_length=200),
        ),
    ]
