# Generated by Django 2.1.3 on 2018-11-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssai', '0002_auto_20181120_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='admit_pic',
            field=models.ImageField(default='pic_folder/default.png', upload_to='pic_folder/'),
        ),
    ]
