# Generated by Django 2.1.3 on 2018-12-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssai', '0005_auto_20181206_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
