# Generated by Django 2.1.3 on 2018-12-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssai', '0006_studentinfo_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='qrcode_img',
            field=models.ImageField(blank=True, null=True, upload_to='pic_folder/'),
        ),
    ]
